piyushgarg-dev/piyushgargdev-nextjs

- components/UI/Hero.jsx
> Wrong Text of the Button on Home Page #2 fixed

- components/UI/Hero.jsx
This PR fixes the typo of "Piyushh" to "Piyush" on the Home page.
Fixes #78
> fix: the typo of Piyush

- components/Header/Header.jsx
Fixes #62 
Added GitHub icon to navbar social media section
Click the GitHub icon and it should open the attached github profile link in a separate tab
> feat: [Fix]-issue #62: added github icon to Navbar social media links

- components/UI/Testimonial.jsx
https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/72803397/140f47e1-69b6-4f31-80e6-03ffaf73c3bd
1. Go to the website in testimonal section
2. Click on Left & Right Buttons
3. They are working now
> Fix: #11 Testimonial's Arrow Keys

- styles/hero.module.css
> fix #13: hero image alignment fixed

- components/UI/PortfolioItem.jsx
- styles/portfolio-item.module.css
This code change will apply hover effect on buttons on Home Page on Courses Section.
Fixes #30 
Before
After
UI Change
- Chore (refactoring code, technical debt, workflow improvements)
1. Go to Home Page of Website.
2. Scroll down till courses section
3. Hover on Buttons of cards.
- I haven't added tests that prove my fix is effective or that my feature works
> Hover Effect Applied on Buttons

- components/UI/Blog.jsx
- components/UI/Courses.jsx
- components/UI/Testimonial.jsx
increase font size of "checkout  my recent vlogs'
Fixes #70
- Chore (refactoring code, technical debt, workflow improvements)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective …
> change the font size 

- components/UI/Services.jsx
Fixes #34 
Added cursor: pointer to the sliding youtube thumbnails 
> fix:  added cursor pointer to the youtube video slider

- README.md
This PR contains a video link to the tutorial which shows how to step by step configure and setup the project.
Fixes #104 
Added a video link
Click the hyperlink and you will be taken to a different tab, where you can view the video tutorial.
> feat:  added video link to setting up tutorial

- CONTRIBUTION.MD
This PR adds a contribution guide for contributors. It addresses issue 112 by providing clear guidelines and instructions for contributors to effectively contribute to the project. The motivation behind this change is to improve the onboarding experience for new contributors and maintain consistency in the contributions. There are no specific dependencies for this change.
Fixes #112 
To test this change, follow these steps:
1. Go through the contribution guide and ensure that all sections are clear and understandable.
2. Verify that the instructions provided in the guide are accurate and up to date.
3. Cross-check the guide with the actual processes of contributing to the project.
4. Ensure that all the links in the guide are …
> feat: Added a contribution guide

- components/UI/PortfolioItem.jsx
fix: Image with src "/images/twitter-clone.jpg" has invalid "height" property. Expected a numeric value in pixels but received "fit-content".
Fixes #95
- [ X] Test A - Simply run yarn dev and you will be able to see the main page without any issue or error related to image height
- [ X ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
> fix: invalid image height fixed

- components/UI/Testimonial.jsx
There is a spelling mistake that needs to be fixed . The spelling of feedback has been written as feedacks.
Fixes #126
Feedback , not feedacks .
-Typo
> fix: typo in feeddacks

- components/UI/Contact.jsx
> fix: contact form container responsive fixed

- components/UI/Contact.jsx
This PR changes the word contact to connect.
Fixes #17 
1. Open the project locally.
2. Check the contact page.
> feat: word change from "contact" to "connect" in contact page 

- components/UI/Testimonial.jsx
- styles/testimonial.module.css
Fixes #91 
https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/35479077/75b3bb46-5de3-4f42-a022-34f66c291dc0
> fix: Testimonials button alignment issue

- components/UI/Services.jsx
What does this PR do?
fixes the spacing issue between the body text and subscribe button inside the services component
Fixes #132
Type of change
Mandatory Tasks
> fix: spacing issue between the text and subscribe button

- components/Header/Header.jsx
- components/UI/Contact.jsx
This PR updates multiple social icons to their filled versions for a consistent visual style throughout the application. The following icons have been changed:
Replaced  `<i className="ri-youtube-fill"></i>` with `<RiYoutubeFill />`
Replaced  `<i className="ri-github-line"></i>`  with  `<RiGithubFill />`
Replaced  `<i className="ri-twitter-fill"></i>`  with  `<RiTwitterFill />`
Replaced  `<i className="ri-linkedin-fill"></i>`  with  `<RiLinkedinFill />`
These changes enhance the overall look and feel of the application while maintaining a cohesive design. No additional dependencies are required for these updates.
Fixes #88 
Previous -
Present -
> feat: Replaced previous social media icons with filled version. 

- components/UI/Courses.jsx
Fixes #140
https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/35479077/dc5ca5bc-31a7-4f4e-96fc-6d0f4dd87a50
> fix: courses card hover effect

- components/UI/Hero.jsx
- styles/subtitle.module.css
🔗This request fixes home Screen layout of hero Component. 👇
- It aligns the profile photo and description as they should be.
- In Mobile view (small/medium devices) it aligns the photo above the description and "join Discord" button.
- It also make small screen UI pretty by aligning Hero items in centre. 
Fixes #36 
As you can see 👇
...............................................**BEFORE**  .....................................................||................................................................. **AFTER**........................................................
-UI fix and Enhanced (no break).
-User experience improved.
Testing this Change is pretty easy.
1️⃣  Go to 'home Screen'
2️⃣ Inspect the web Site if on pc to see the …
> fix: #36  added mobile view for hero Component/fixed UI for small devices.

- components/Header/Header.jsx
What does this PR do?
fixes the syntax error and navigation issues inside the header component 
Fixes #161
Type of change
Mandatory Tasks
> fix: header style and syntax error

- components/Header/header.module.css
- styles/contact.module.css
fix #118 
Added hover effect on the social media icons.
Screenshot:
> fix: #118 Added hover effect on the social media icons.

- components/UI/Contact.jsx
- components/UI/Services.jsx
- styles/globals.css
What does this PR do?
Fix: form look and layout, mobile layout shift and arrow of slider component and video date style 
Fixes #129
Fixes #35
Type of change
> fix: form look and layout, mobile layout shift and arrow of slider component and video date style 

- components/UI/Contact.jsx
- styles/contact.module.css
What does this PR do?
This PR adds the hover effect on the social media icons in Contact page.
Fixes #131 
https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110960043/8293d03f-0461-4742-a9b3-7dbcae5c641e
How should this be tested?
1. Open project locally at port 3000
2. Locate the social media icons In the contact Page.
3. Hover on the icons. The color will get changed to theme color.
- [X ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
Thank You :)
> feat: Implemented hover On Social Media buttons In Contact page.

- components/UI/Contact.jsx
This PR aims to fix the Contact Me Text Alignment with the Contact Me Submission Form.
Fixes #154
Screenshots:
Before: 
After:
> fix: Contact me Text Alignment

- components/Header/Header.jsx
This PR adds the hover effect on the social media icons in header. Hover effect adds bread to butter.
Fixes #175 
Video=>
https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/110960043/3fd8f624-12e0-482b-ab65-fe106c888ef7
1. Open project locally at [click](http://localhost:3000/)
2. Locate the social media icons on the top right in navbar.
3. Hover on the icons. The color will get changed from white to theme color.
> feat: Added hover On Social Media Icons again

- components/Header/Header.jsx
This PR adds a transition ease-in-out effect on the social media icons for better UI/UX
Fixes #206 
https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/126576749/8f66cd09-182c-470e-b963-81fbfbe21a0b
Simple css changes added hover translate 
- Visit Home page 
- Hover your mouse on top-right side icon
> [feat]:hover icon transition on navbar icons

- components/UI/Hero.jsx
This PR changes the discord icon on Homepage 
Fixes #715
> Added Discord Icon on Home Page

- styles/contact.module.css
- yarn.lock
I fixed the bug related to CSS.
I set a 4px margin-left to the social links section in the Contact.jsx component of thepiyushgargdev-nextjs repository.
Fixes #869 
Ui related issue fixed
> bug fixed : Align the connect to me section properly

- components/Header/Header.jsx
- components/UI/Contact.jsx
- components/UI/NewTwitterlogo.jsx
This PR fixes Twitter logo to X
Fixes #841
> fix : Twitter logo to X

- components/UI/Contact.jsx
It adds a hover effect to the email element within the contact page to provide a visual indication of interactivity. Previously, the email element lacked this behavior, making it less clear to users that it was clickable.
Fixes #851
[fix hover effect.webm](https://github.com/piyushgarg-dev/piyushgargdev-nextjs/assets/57056757/d860da2a-b660-4032-8db0-db673f7c4109)
> fix: Hover Effect Applied to Email
